name: Deploy to AWS S3 + CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build static site
        run: CI=true yarn build

      - name: Upload only posts to S3
        uses: jakejarvis/s3-sync-action@master # 또는 @v0.5.1
        with:
          args: >
            --delete
            --exclude "*"
            --include "posts/*"
        env:
          AWS_S3_BUCKET: muke.co.kr
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2
          SOURCE_DIR: out

      - name: Get changed posts files
        id: changed-posts
        run: |
          echo "PATHS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} \
            | grep '^out/posts/.*' \
            | sed 's/^out//g' \
            | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Invalidate CloudFront cache for posts
        if: env.PATHS != ''
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_REGION: ap-northeast-2
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS: ${{ env.PATHS }}
